#!/usr/bin/env sh

set nonomatch
rm -rf generated_settings .tox
rm -rf .cache

# the rest is common to all python directories
rm -f *.pyc *.pyo
rm -f .test*.sum expected result install.out .*.log
rm -rf build *.egg-info dist __pycache__ .eggs .mypy_cache
rm -rf **/{__pycache__,*.pyc,*.pyo,.mypy_cache}
rm -rf .coverage .coverage-html htmlcov .tox
rm -rf .pytest_cache .cache dist .build quantiphy.egg.info
rm -rf tests/{htmlcov,.cache,.coverage,.pytest_cache}
rm -rf doc/.build
